### ISSUE TITLE
Broken my sshd

### ISSUE THREAD

**Issue by mjdavies** [willshersystems/ansible-sshd#100]
Hi Everyone

I've used ansible-sshd to secure my sshd on my server, but now future runs of ansible-sshd are failing.

Server is running centos7 with OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017

Here's the error I'm getting when trying to change the settings

```
fatal: [tooling1]: FAILED! => {
    "assertion": "__sshd_os_supported == True",
    "changed": false,
    "evaluated_to": false
}
```

Here's the variables I used to secure

```
sshd_skip_defaults: false
sshd_allow_reload: false
sshd:
  KexAlgorithms: "curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256"
  X11Forwarding: false
  Protocol: 2
  HostKey:
    - "/etc/ssh/ssh_host_ed25519_key"
    - "/etc/ssh/ssh_host_rsa_key"
  PasswordAuthentication: false
  ChallengeResponseAuthentication: false
  PubkeyAuthentication: true
  Ciphers: "chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr"
  MACs: "hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com"
```

And here's the resulting sshd_config file

```
# Ansible managed
Protocol 2
HostKey /etc/ssh/ssh_host_ed25519_key
HostKey /etc/ssh/ssh_host_rsa_key
AcceptEnv LANG LC_CTYPE LC_NUMERIC LC_TIME LC_COLLATE LC_MONETARY LC_MESSAGES
AcceptEnv LC_PAPER LC_NAME LC_ADDRESS LC_TELEPHONE LC_MEASUREMENT
AcceptEnv LC_IDENTIFICATION LC_ALL LANGUAGE
AcceptEnv XMODIFIERS
AuthorizedKeysFile .ssh/authorized_keys
ChallengeResponseAuthentication no
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
GSSAPIAuthentication yes
GSSAPICleanupCredentials yes
KexAlgorithms curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com
PasswordAuthentication no
PubkeyAuthentication yes
Subsystem sftp /usr/libexec/openssh/sftp-server
SyslogFacility AUTHPRIV
UsePAM yes
UsePrivilegeSeparation sandbox
X11Forwarding no
```
I can ssh into the machine without a problem

Anyone got any ideas what's going on?

Thanks
