### ISSUE TITLE
subsystem appears to be ignored

### ISSUE THREAD

**Issue by grimreaper** [willshersystems/ansible-sshd#119]
With the following config
```
- src: willshersystems.sshd
  version: v0.8.1
```

```
sshd:
  Compression: yes
  ListenAddress:
    - "0.0.0.0"
    - "::"
  AllowAgentForwarding: yes
  AllowGroups: ssh_allowed
  AuthenticationMethods: publickey
  PermitRootLogin: no
  Port: 22
  UseDNS: no
  Subsystem: "sftp internal-sftp"
```
I get the following sshd_config
```
# Ansible managed
Port 22
ListenAddress 0.0.0.0
ListenAddress ::
AllowAgentForwarding yes
AllowGroups ssh_allowed
AuthenticationMethods publickey
Compression yes
PermitRootLogin no
UseDNS no
```

Note the lack of "Subsystem" in the second block. Am I missing something?
