### ISSUE TITLE
Proposition to manage SSH Certificates

### ISSUE THREAD

**Issue by Clement87** [willshersystems/ansible-sshd#177]
Hi,   
I'm using this role in addition to an other one I made to manage SSH Certificats with Principals.
What are your thoughts if I submit a PR.

The change will look something like this:

### Add 3 tasks

```
- name: Copy Trusted user CA Keys
  ansible.builtin.template:
    src: "trusted-user-ca-keys.pem.j2"
    dest: "/etc/ssh/trusted-user-ca-keys.pem"
  when: sshd_trusted_user_ca_keys_list is not none

- name: Create Pincipals directory
  ansible.builtin.file:
    path: /etc/ssh/auth_principals/
    state: directory
    mode: '0755'
  when: sshd_principals is not none

- name: Copy Pincipals files
  ansible.builtin.template:
    src: "auth_principals.j2"
    dest: "/etc/ssh/auth_principals/{{ item.key }}"
    mode: '0644'
  loop: "{{ q('dict', sshd_principals) }}"
  when: sshd_principals is not none
```

### Add 2 templates

trusted-user-ca-keys.pem.j2
```
{% for key in sshd_trusted_user_ca_keys_list %}
{{ key }}
{% endfor %}
```

auth_principals.j2
```
{% for principal in item.value %}
{{ principal }}
{% endfor %}
```

### Example of values

```
sshd_trusted_user_ca_keys_list:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxITsDG2UVFYMUfh4Q==

# Key is the user in the os, values are *Principals* defined in the certificate
sshd_principals:
  admin:
    - frontend-admin
    - backend-admin
  somelinuxuser: 
    - some-principal-defined-in-certificate
```

And of course, we would like to set this configuration:
```
sshd:
  PasswordAuthentication: no
  TrustedUserCAKeys: /etc/ssh/trusted-user-ca-keys.pem
  AuthorizedPrincipalsFile: "/etc/ssh/auth_principals/%u"
```

To learn more about SSH Certificate, here is a [nice tutorial from Hashicorp](https://www.hashicorp.com/blog/managing-ssh-access-at-scale-with-hashicorp-vault)

Best, 
Clement
