### ISSUE TITLE
Whats the best way to comment out a default configuration parameter

### ISSUE THREAD

**Issue by fleroux514** [willshersystems/ansible-sshd#180]
I am currently using the role by only configuring the `sshd` variable this way:

```
sshd:
  GSSAPIAuthentication: 'no'
  PasswordAuthentication: 'no'
  PubkeyAuthentication: 'no'
  Match:
    - Condition: User root,ansible
      PubkeyAuthentication: 'yes'
      PasswordAuthentication: 'yes'
      GSSAPIAuthentication: 'no'
```

So along with the specified configuration above, all default OS configuration parameters are generated in `/etc/ssh/sshd_config`.

I have a special case where I wish to configure most of the default configuration except for the `AuthorizedKeysFile` parameter that I want to omit or comment out from the config.

I know that I could set the `sshd_AuthorizedKeysFile` variable to change it's default value, but not sure how to comment it out (even tried  setting `sshd_#AuthorizedKeysFile` )

Is there any way to achieve this without setting `sshd_skip_defaults` to true and having to specify all parameters?

Thanks
