### ISSUE TITLE
Role creates /root/sshd directory on debian

### ISSUE THREAD

**Issue by Yannik** [willshersystems/ansible-sshd#264]
On debian (10/11/12), the `vars` file contains this line:

```
__sshd_runtime_directory: sshd
```

In `install.yml`, the following task is executed:

```
    - name: Make sure sshd runtime directory is present
      ansible.builtin.file:
        path: "{{ __sshd_runtime_directory }}"
        state: directory
        owner: root
        group: root
        mode: "{{ __sshd_runtime_directory_mode }}"
      when:
        - __sshd_runtime_directory is not none
```

This results in an directory `/root/sshd` being created. (Assuming ansible_user is root)

Obviously, this serves no purpose and should not be done.
