### ISSUE TITLE
Ansible Galaxy: no more version?

### ISSUE THREAD

**Issue by Sispheor** [willshersystems/ansible-sshd#266]
There is no version in galaxy

![image](https://github.com/willshersystems/ansible-sshd/assets/2573405/27ff8715-9f1b-4c2b-9687-e350d5c66544)

**Comment by richm** [comment]
There is currently a bug in the new Galaxy - https://github.com/ansible/galaxy_ng/pull/1946

**Comment by mattwillsher** [comment]
Work around in requirements file:

```yaml
- name: willshersystems.sshd
  src: https://github.com/willshersystems/ansible-sshd
  version: v0.22.0
```
