### ISSUE TITLE
Setting up second sshd service is broken since last release

### ISSUE THREAD

**Issue by Jakuje** [willshersystems/ansible-sshd#280]
The generated service file will always have the path to the `sshd_main_config_file`, which is defined since 6bb0d7b456eececcf5b5e0c817b113cfde98d170, but was never documented and its usage is somewhat confusing, which I missed initially.

The `sshd_main_config_file` can be overridden by the user, but it is not what was needed to set up the second service before f6ae2094fe23eed94ce64eee1d0f5f1109dfe1da, which used the `sshd_config_file` directly.

The 6bb0d7b456eececcf5b5e0c817b113cfde98d170 makes some operation depending on the following condition which I do not completely understand:
 * `sshd_config_file | dirname != sshd_main_config_file | dirname`

By default the `sshd_config_file` is `/etc/ssh/sshd_config.d/something` and `sshd_main_config_file` is `/etc/ssh/sshd_config`, which means this condition is not matched for default configuration, which is expected. It is used in the following contexts:
 * prevention to write default in the configuration file in drop-in directory
 * creation of drop-in directory
 * checking the main configuration file contains the include directive

It is basically just checking the files are not in the same directory, which works ok if want to detect the second service's configuration file such as `/etc/ssh/sshd_config2`, but fails in cases when the file is in completely different directory, such as `/etc/ssh2/sshd_config`.

Previously, there was a `__sshd_drop_in_dir`, which allowed us to check if the configuration file we are writing is in the drop-in directory to do the above, or its file for separate service in different path, but this does not work anymore

~My proposal would be to refine the above condition to check the `sshd_config_file` is under the dirname of `__sshd_defaults.Include` (it should be able to make up the path even if it is with the star expansion).~

Edit: The first proposal wont work as the `Inlcude` directive is now based on the `sshd_config_file`'s `dirname`. 

More info: https://issues.redhat.com/browse/RHEL-29309

**Comment by Jakuje** [comment]
One option might be to require the `sshd_main_config_file`, which I am not much happy about as this worked before.

Other option might be applying some heuristics to find out if the `sshd_config_file` points to a file which is and which should be included in the main configuration file or not.

I think that the current behavior will even "break" the main sshd service as it will likely try to modify the original `sshd_config` to contain `Include /etc/ssh2/*.conf` if I see right.

Adding the playbook, which is used in the test:
```
---
- name: Configure second SSHD service on different port
  hosts: all
  vars:
    sshd_service: sshd2
    sshd_config_file: /etc/ssh2/sshd_config
    sshd_install_service: true
    sshd_manage_selinux: true
    sshd:
      Port: 2222
      ForceCommand: echo "CONNECTED2"
  tasks:
    - name: Run the role
      ansible.builtin.include_role:
        name: linux-system-roles.sshd
```
