### ISSUE TITLE
Failure on RHEL8 due to non existing sshd_config.d

### ISSUE THREAD

**Issue by skwde** [willshersystems/ansible-sshd#282]
When running the role like

```yml
- name: Handle default sshd_config for RHEL8
  ansible.builtin.include_role:
    name: fedora.linux_system_roles.sshd
  vars:
    sshd_skip_defaults: false # noqa var-naming[no-role-prefix]
    sshd_config_file: "/etc/ssh/sshd_config"
    # sshd: {}
```

on a fresh install of RHEL8 without an existing `/etc/sshd_config.d` execution fails with the message

```
Destination directory /etc/ssh/sshd_config.d does not exist
```

**Comment by richm** [comment]
@Jakuje is this issue fixed by https://github.com/willshersystems/ansible-sshd/pull/281 ?

**Comment by Jakuje** [comment]
> @Jakuje is this issue fixed by #281 ?

I think so. I just installed the RHEL8 VM and the above task no longer throws this error with the changes.

@skwde can you double-check with the changes proposed in #281?

**Comment by skwde** [comment]
I installed the role from `https://github.com/Jakuje/ansible-sshd.git,main_config_file` and ran

```sh
---
- name: Handle default sshd_config for RHEL8
  ansible.builtin.include_role:
    name: ansible-sshd
  vars:
    sshd_skip_defaults: false # noqa var-naming[no-role-prefix]
    sshd_config_file: "/etc/ssh/sshd_config"
    # sshd: {}

```

which failed with the same error.

I also tried running

```yml
---
- name: Handle default sshd_config for RHEL8
  ansible.builtin.include_role:
    name: ansible-sshd
  vars:
    sshd_skip_defaults: false # noqa var-naming[no-role-prefix]
    sshd_config_file: "/etc/ssh/sshd_config"
    sshd_main_config_file: None
    # sshd: {}
```

but got the same error.

**Comment by Jakuje** [comment]
Can you paste the whole error message you are getting, ideally with the `-vv` added to the `ansible-playbook` when executed and with the task name failing? I believe it should be from the task `Create a directory for drop-in configuration snippets`, but in the #281, it should not be executed when `sshd_main_config_file is none` and RHEL8 should have this variable set to none as it does not have the drop-in directory by default.

**Comment by skwde** [comment]
From the shell history I was able to dig up the task:

```out
TASK [fedora.linux_system_roles.sshd : Create the complete configuration file]
```

I can however no longer test it easily because I already deployed the workaround to the production systems.

**Comment by skwde** [comment]
Here is the `vars/sshd.yml`

```yml
---
# ## sshd variables, see
# ##   https://github.com/willshersystems/ansible-sshd
# ## for a description

# sshd_manage_service: true
# sshd_allow_reload: true

sshd_install_service: false

sshd_manage_firewall: false
sshd_manage_selinux: false

sshd_backup: false

sshd_sysconfig: false
sshd_sysconfig_override_crypto_policy: false
sshd_sysconfig_use_strong_rng: 0
# sshd_main_config_file: /etc/ssh/sshd_config
# sshd_config_file: /etc/ssh/sshd_config.d/<include snippet>.conf

# sshd_config_namespace: null

# sshd_config_owner:
# sshd_config_group:
# sshd_config_mode:

# sshd_verify_hostkeys: auto

# sshd_hostkey_owner:
# sshd_hostkey_group:
# sshd_hostkey_mode:

```

which is included before following tasks run.

```yml
- name: Handle default sshd_config for RHEL8
  ansible.builtin.include_role:
    name: fedora.linux_system_roles.sshd
  vars:
    sshd_skip_defaults: false # noqa var-naming[no-role-prefix]
    sshd_config_file: "/etc/ssh/sshd_config"
    # sshd: {}

- name: IPA
  ansible.builtin.include_role:
    name: fedora.linux_system_roles.sshd
  vars:
    sshd_skip_defaults: true # noqa var-naming[no-role-prefix]
    sshd_config_file: "/etc/ssh/sshd_config.d/04-ipa.conf"
    sshd:
      PubkeyAuthentication: "yes"
      KerberosAuthentication: "no"
      GSSAPIAuthentication: "yes"
      UsePAM: "yes"
      ChallengeResponseAuthentication: "yes"
      AuthorizedKeysCommand: /usr/bin/sss_ssh_authorizedkeys
      AuthorizedKeysCommandUser: nobody
```

No other sshd related variables are set.
