### ISSUE TITLE
Cannot override role values from group vars

### ISSUE THREAD

**Issue by jeffwidman** [willshersystems/ansible-sshd#29]
Nice role--you cover a lot of handy stuff. 

However, I noticed you've put a lot of variables in /vars/ rather than /defaults/ which makes it so I can't override the values without manually modifying the role: http://stackoverflow.com/questions/26475071/ansible-playbook-group-var-being-overriden-by-a-role-var

Would you be open to moving a bunch of the params to /defaults/? 

My preference is to manage all my ansible-galaxy roles in one folder, and then individual project playbooks override various role parameters as needed: http://stackoverflow.com/questions/22201306/ansible-galaxy-roles-install-in-to-a-specific-directory/32728042#32728042

It just makes life easier as that way I only have one role to maintain, but can adjust values as necessary for each project. 

For example, right now my playbooks can't override any of the values in here: 
For example, most of the values here: https://github.com/willshersystems/ansible-sshd/blob/master/vars/RedHat_7.yml

**Comment by mattwillsher** [comment]
Hi Jeff,

What in particular where you looking to override?

**Comment by jeffwidman** [comment]
Here are the main variables that tend to vary by playbook:
```
permit_empty_passwords: no
permit_root_login: no
password_authentication: no
challenge_response_authentication: no
use_pam: yes
```

**Comment by mattwillsher** [comment]
Hi Jeff,

Sorry the delay in getting back to you.

They can be overridden - the values in the vars are just defaults (perhaps somewhat counter intuitively :) ) and used in the template. IIF a value is not set then the default is set to the value from the ssh_defaults: dict set is vars. If you set the sshd dict:

```yaml
sshd:
  permit_empty_passwords: no
  permit_root_login: no
  password_authentication: no
  challenge_response_authentication: no
  use_pam: yes
```

that will override the values from the var file. Alternatively:

```yaml
sshd_permit_empty_passwords: no
sshd_permit_root_login: no
etc.
```
for cases where you want to set different vars at different locations and not override the whole of sshd.
