### ISSUE TITLE
best practices

### ISSUE THREAD

**Issue by ryanolson** [willshersystems/ansible-sshd#46]
It would be great if you provided a hardened / best practices example playbook.

**Comment by mattwillsher** [comment]
Do you have anything particularly in mind? I'm aware of the CIS Benchmarks that may have some parts, and PCI may too.

**Comment by mattwillsher** [comment]
Will review https://github.com/dev-sec/ansible-ssh-hardening with a view to providing examples for this role.

**Comment by jauderho** [comment]
I would use https://stribika.github.io/2015/01/04/secure-secure-shell.html  as a starting point.

**Comment by pdreker** [comment]
Based on the aforementioned stribika.github.io article:
```
sshd:
  KexAlgorithms:
    - curve25519-sha256@libssh.org
    - diffie-hellman-group-exchange-sha256
  Protocol: 2
  HostKey:
    - /etc/ssh/ssh_host_rsa_key
    - /etc/ssh/ssh_host_ed25519_key
  PasswordAuthentication: "no"
  PermitRootLogin: prohibit-password
  ChallengeResponseAuthentication: "no"
  PubkeyAuthentication: "yes"
  AllowGroups: ssh_allow
  Ciphers: chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
  MACs: hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-ripemd160-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,hmac-ripemd160,umac-128@openssh.com
```
This implements the "maximum" recommendation from the blog artcle and we use it in production here. Be aware that this locks out older PuTTY clients, which do not support the needed EC Algorithms and Users need to be in an explicit group named "ssh_allow" to be able to actually login via ssh.

Also this needs some more Ansible Code to remove unneeded hostkeys from /etc/ssh/ and an Ansible Module to regenerate hostkeys, if they do not have the appropiate strength. Further one needs to generate a new /etc/moduli file with long moduli only and distribute this to the servers. In addition to this: don't forget to deploy an /etc/ssh/ssh_config with the appropiate settings.

**Comment by pdreker** [comment]
Matching SSH Config: https://gist.github.com/pdreker/f843dd4bee920b63e06ac7aebd54a91a

**Comment by D4N** [comment]
FYI: `hmac-ripemd160-etm@openssh.com` and `hmac-ripemd160` got removed in one of the last openssh server releases, so adding them to `MACs` can lead to nasty surprises (= sshd not starting).

My current sshd config (also based on the aforementioned blogpost looks like this):
```
    sshd_skip_defaults: false
    sshd_allow_reload: false
    sshd:
      KexAlgorithms: "curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256"
      X11Forwarding: false
      Protocol: 2
      HostKey:
        - "/etc/ssh/ssh_host_ed25519_key"
        - "/etc/ssh/ssh_host_rsa_key"
      PasswordAuthentication: false
      ChallengeResponseAuthentication: false
      PubkeyAuthentication: true
      Ciphers: "chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr"
      MACs: "hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com"
```
There is also another set of guidelines from mozilla: https://infosec.mozilla.org/guidelines/openssh and a ssh checker https://sshcheck.com
