### ISSUE TITLE
sshd_skip_defaults: true getting ignored?

### ISSUE THREAD

**Issue by jseiser** [willshersystems/ansible-sshd#69]
I dont seem able to get anything but the OS defaults to apply. I want to modify the CIPHERS and MACs but cant seem to get it to go.

My play looks like this.

```
    - name: willshersystems.sshd
      include_role:
        name: willshersystems.sshd
      tags:
        - sshd
```

my groupvars for the hosts look like this.

```
sshd_skip_defaults: true
sshd_config_mode: '0644'
sshd_packages:
  - openssh
  - openssh-server
sshd_sftp_server: /usr/libexec/openssh/sftp-server
sshd:
  SyslogFacility: AUTHPRIV
  PermitRootLogin: forced-commands-only
  AuthorizedKeysFile: .ssh/authorized_keys
  PasswordAuthentication: no
  ChallengeResponseAuthentication: no
  UsePAM: yes
  X11Forwarding: yes
  PrintLastLog: yes
  UsePrivilegeSeparation: sandbox
  AcceptEnv:
    - LANG LC_CTYPE LC_NUMERIC LC_TIME LC_COLLATE LC_MONETARY LC_MESSAGES
    - LC_PAPER LC_NAME LC_ADDRESS LC_TELEPHONE LC_MEASUREMENT
    - LC_IDENTIFICATION LC_ALL LANGUAGE
    - XMODIFIERS
  Subsystem: "sftp {{ sshd_sftp_server }}"
  Ciphers:
    - chacha20-poly1305@openssh.com
    - aes256-gcm@openssh.com
    - aes128-gcm@openssh.com
    - aes256-ctr
    - aes192-ctr
    - aes128-ctr
  MACs:
    - hmac-sha2-512-etm@openssh.com
    - hmac-sha2-256-etm@openssh.com
    - hmac-ripemd160-etm@openssh.com
    - umac-128-etm@openssh.com
    - hmac-sha2-512
```

Yet when I run the playbook, I just end up with the default sshd for Amazon linux.  There must be something I am missing.
